### ISSUE TITLE
refactor(angular2): Update to Angular2 RC

### ISSUE THREAD

**Issue by hboylan** [angular/angular-electron#16]
Looks like there hasn't been much progress here since Angular2 moved from Beta to RC.

**Comment by kazemihabib** [comment]
+1

**Comment by leifwells** [comment]
I've attempted to update this code to rc.1 twice and I keep getting stopped by the same problems:
1. There are many, many imports from `@angular/platform-browser/src/web_workers/` but that folder doesn't exist in my node_modules folder and I get a TypeScript error on the import line. I must be doing something wrong here, because the code is obviously in the repo. 
2. There is an import for `CONST_EXPR` but it is not in the module that the other imports around it are in. For instance: `import {Type, CONST_EXPR, isPresent} from '@angular/core/src/facade/lang';`
3. I changed `import {DOM} from 'angular2/src/platform/dom/dom_adapter';` to `import {getDOM} from '@angular/platform-browser/src/dom/dom_adapter';` but I have no idea if that is acceptable
4. I changed `import {platform} from 'angular2/core';` to `import { PlatformRef } from '@angular/core';`, again, no idea if that is acceptable.

So, sadly, I am not the developer who can make this happen. Perhaps one of the original contributors could assist with this.

Also, I would absolutely love to see a presentation on this code. There are several things going on here that I don't understand completely and wish there was an article or video post about it to shed more light.

**Comment by elmergu** [comment]
anybody knows if this projects still active, any chance it will be updated to angular RC ?

**Comment by hboylan** [comment]
Doesn't look like it 😞

**Comment by sqwk** [comment]
It probably pays to wait for rc2 before doing anything. After that, I am also very much willing to help, also to get multiple window support working. (See #19)

**Comment by petlego** [comment]
@robwormald  ... any hope for an update with the arrival of RC3?

**Comment by HalfLegend** [comment]
RC5 has arrived, but still no update.
The project is dead

**Comment by datiecher** [comment]
So Angular 2 final has been released some time ago. Any plans to keep this project going or is it truly dead?

**Comment by robwormald** [comment]
back to working on it now. I've got a functional 2.0.1 build i'll try to get pushed this week.

**Comment by elmergu** [comment]
Hi @robwormald, sorry to insist but can we expect this week the update?
